const fs = require('fs');
const path = require('path');

const htmlPath = path.join(__dirname, '..', 'src', 'components', 'landing-page.html');
let html = fs.readFileSync(htmlPath, 'utf8');

const saasKeysEn = `
        mAttendanceLabel: "CLASS ATTENDANCE",
        mAttendanceSub: "▲ 100% Present",
        mNapLabel: "NAP STATUS",
        mMealLabel: "MEAL SUCCESS",
        mMealSub: "▲ 18/18 Eaten",
        mMedicationLabel: "MEDICATIONS",
        classRosterTitle: "📋 Little Explorers Class Roster",
        roomLabel: "Room 102",
        thChildName: "Child Name",
        thAge: "Age",
        thMeal: "Meal",
        thNap: "Nap",
        thMedication: "Medication",
        statusMeal100: "✔ 100% Eaten",
        statusMeal75: "✔ 75% Eaten",
        statusPending14: "Pending (14:00)",
        statusPending16: "Pending (16:00)",
        statusNone: "None",
        logEntryTitle: "✍️ Log Entry & Family Sync",
        lblSelectChild: "Select Child",
        lblMealStatus: "Meal Log Status",
        optMeal100: "Lunch: 100% Eaten",
        optMeal75: "Lunch: 75% Eaten",
        optMeal50: "Lunch: 50% Eaten",
        btnSaveNotify: "Save & Notify Family ➜",
        schedTitle: "📅 Today's Class Schedule",
        schedItem1: "🎨 Morning Arts & Crafts",
        schedItem2: "🥗 Healthy Lunch Service",
        schedItem3: "💤 Nap & Rest Time",
        liveStreamTitle: "⚡ Real-Time Family Activity Feed",
        mTotalResidents: "TOTAL RESIDENTS",
        mActiveInfirmary: "ACTIVE INFIRMARY",
        mVitalsChecked: "VITALS CHECKED",
        mMedAlerts: "CRITICAL MED ALERTS",
        residentVitalsTitle: "👵 Resident Vitals & Health Monitor",
        thResident: "Resident Name",
        thRoom: "Room",
        thBP: "Blood Pressure",
        thPulse: "Pulse",
        thBloodSugar: "Blood Sugar",
        medFormTitle: "💊 Quick Med Administration",
        lblResident: "Select Resident",
        lblMedType: "Medication Type",
        btnLogMed: "Log Medication & Notify Doctor ➜",
        familyFeedTitle: "👨‍👩‍👧 Family Feed for Mila Yılmaz",
        familyFeedDesc: "Today's Timeline Summary & Live Photo Updates:",
        msgTeacherTitle: "📩 Message Teacher / Request Med",
        lblMessageNote: "Note for Teacher",
        btnSendTeacher: "Send Message ➜",
        mRevenueLabel: "MONTHLY REVENUE",
        mOccupancyLabel: "OCCUPANCY RATE",
        mActiveStaff: "ACTIVE STAFF",
        mSatisfaction: "FAMILY SATISFACTION",
        mgrReportsTitle: "📊 Facility Financial & Operational Reports",
        mgrReportsDesc: "Export monthly billing, occupancy reports, and staff logs:",
        btnExportPdf: "Export PDF Report 📄",
        btnMassSms: "Send Mass Announcement 📱",
        staffStatusTitle: "👥 Staff Shift Status",
        btnExitApp: "🚪 Exit App to Landing Page",
        btnLandingPage: "Landing Page ➜"`;

const saasKeysTr = `
        mAttendanceLabel: "SINIF KATILIMI",
        mAttendanceSub: "▲ %100 Katılım",
        mNapLabel: "UYKU DURUMU",
        mMealLabel: "YEMEK BAŞARISI",
        mMealSub: "▲ 18/18 Yenildi",
        mMedicationLabel: "BEKLEYEN İLAÇLAR",
        classRosterTitle: "📋 Minik Kaşifler Sınıf Listesi",
        roomLabel: "Derslik 102",
        thChildName: "Öğrenci Adı",
        thAge: "Yaş",
        thMeal: "Yemek",
        thNap: "Uyku",
        thMedication: "İlaç Durumu",
        statusMeal100: "✔ %100 Yenildi",
        statusMeal75: "✔ %75 Yenildi",
        statusPending14: "Bekliyor (14:00)",
        statusPending16: "Bekliyor (16:00)",
        statusNone: "Yok",
        logEntryTitle: "✍️ Kayıt Girişi & Veli Bildirimi",
        lblSelectChild: "Öğrenci Seçin",
        lblMealStatus: "Yemek Durumu",
        optMeal100: "Öğle: %100 Yenildi",
        optMeal75: "Öğle: %75 Yenildi",
        optMeal50: "Öğle: %50 Yenildi",
        btnSaveNotify: "Kaydet & Veliye Bildir ➜",
        schedTitle: "📅 Bugünün Sınıf Programı",
        schedItem1: "🎨 Sabah Resim & El Sanatları",
        schedItem2: "🥗 Sağlıklı Öğle Yemeği",
        schedItem3: "💤 Uyku & Dinlenme Zamanı",
        liveStreamTitle: "⚡ Gerçek Zamanlı Aile Aktivite Akışı",
        mTotalResidents: "TOPLAM SAKİNLER",
        mActiveInfirmary: "AKTİF REVİR",
        mVitalsChecked: "VİTAL BULGULAR",
        mMedAlerts: "KRİTİK İLAÇ ALARMLARI",
        residentVitalsTitle: "👵 Sakin Vital Bulguları & Sağlık Takibi",
        thResident: "Sakin Adı",
        thRoom: "Oda",
        thBP: "Tansiyon",
        thPulse: "Nabız",
        thBloodSugar: "Şeker",
        medFormTitle: "💊 Hızlı İlaç Uygulaması",
        lblResident: "Sakin Seçin",
        lblMedType: "İlaç Türü",
        btnLogMed: "İlacı Kaydet & Doktora Bildir ➜",
        familyFeedTitle: "👨‍👩‍👧 Mila Yılmaz Aile Akışı",
        familyFeedDesc: "Bugünün Zaman Çizelgesi Özet & Canlı Güncellemeleri:",
        msgTeacherTitle: "📩 Öğretmene Mesaj / İlaç Talebi",
        lblMessageNote: "Öğretmene Not",
        btnSendTeacher: "Mesajı Gönder ➜",
        mRevenueLabel: "AYLIK GELİR",
        mOccupancyLabel: "DOLULUK ORANI",
        mActiveStaff: "AKTİF PERSONEL",
        mSatisfaction: "VELİ MEMNUNİYETİ",
        mgrReportsTitle: "📊 Tesis Finansal & Operasyonel Raporlar",
        mgrReportsDesc: "Aylık fatura, doluluk ve personel raporlarını dışa aktarın:",
        btnExportPdf: "PDF Rapor Al 📄",
        btnMassSms: "Toplu Duyuru Gönder 📱",
        staffStatusTitle: "👥 Personel Vardiya Durumu",
        btnExitApp: "🚪 Landing Page'e Dön",
        btnLandingPage: "Landing Page ➜"`;

const saasKeysEs = `
        mAttendanceLabel: "ASISTENCIA A CLASE",
        mAttendanceSub: "▲ 100% Presentes",
        mNapLabel: "ESTADO DE SUEÑO",
        mMealLabel: "ÉXITO EN COMIDAS",
        mMealSub: "▲ 18/18 Consumidos",
        mMedicationLabel: "MEDICAMENTOS PENDIENTES",
        classRosterTitle: "📋 Lista de Clase Pequeños Exploradores",
        roomLabel: "Aula 102",
        thChildName: "Nombre del Niño",
        thAge: "Edad",
        thMeal: "Comida",
        thNap: "Sueño",
        thMedication: "Medicamento",
        statusMeal100: "✔ 100% Consumido",
        statusMeal75: "✔ 75% Consumido",
        statusPending14: "Pendiente (14:00)",
        statusPending16: "Pendiente (16:00)",
        statusNone: "Ninguno",
        logEntryTitle: "✍️ Entrada de Registro y Sincronización",
        lblSelectChild: "Seleccionar Niño",
        lblMealStatus: "Estado de Comida",
        optMeal100: "Almuerzo: 100% Consumido",
        optMeal75: "Almuerzo: 75% Consumido",
        optMeal50: "Almuerzo: 50% Consumido",
        btnSaveNotify: "Guardar y Notificar a la Familia ➜",
        schedTitle: "📅 Horario de Clase de Hoy",
        schedItem1: "🎨 Arte y Manualidades Matutinas",
        schedItem2: "🥗 Servicio de Almuerzo Saludable",
        schedItem3: "💤 Hora de Siesta y Descanso",
        liveStreamTitle: "⚡ Feed de Actividad Familiar en Tiempo Real",
        mTotalResidents: "TOTAL RESIDENTES",
        mActiveInfirmary: "ENFERMERÍA ACTIVA",
        mVitalsChecked: "SIGNOS VITALES",
        mMedAlerts: "ALERTAS CRÍTICAS",
        residentVitalsTitle: "👵 Monitor de Signos Vitales de Residentes",
        thResident: "Nombre del Residente",
        thRoom: "Habitación",
        thBP: "Presión Arterial",
        thPulse: "Pulso",
        thBloodSugar: "Glucosa",
        medFormTitle: "💊 Administración Rápida de Medicamentos",
        lblResident: "Seleccionar Residente",
        lblMedType: "Tipo de Medicamento",
        btnLogMed: "Registrar y Notificar al Médico ➜",
        familyFeedTitle: "👨‍👩‍👧 Feed Familiar para Mila Yılmaz",
        familyFeedDesc: "Resumen de la Cronología de Hoy:",
        msgTeacherTitle: "📩 Mensaje al Profesor / Solicitar Medicamento",
        lblMessageNote: "Nota para el Profesor",
        btnSendTeacher: "Enviar Mensaje ➜",
        mRevenueLabel: "INGRESOS MENSUALES",
        mOccupancyLabel: "TASA DE OCUPACIÓN",
        mActiveStaff: "PERSONAL ACTIVO",
        mSatisfaction: "SATISFACCIÓN FAMILIAR",
        mgrReportsTitle: "📊 Informes Financieros y Operativos",
        mgrReportsDesc: "Exportar facturación mensual y registros de personal:",
        btnExportPdf: "Exportar Informe PDF 📄",
        btnMassSms: "Enviar Anuncio Masivo 📱",
        staffStatusTitle: "👥 Estado del Turno de Personal",
        btnExitApp: "🚪 Volver a Landing Page",
        btnLandingPage: "Landing Page ➜"`;

const saasKeysZh = `
        mAttendanceLabel: "出勤率",
        mAttendanceSub: "▲ 100% 在班",
        mNapLabel: "午睡状态",
        mMealLabel: "就餐完成度",
        mMealSub: "▲ 18/18 用餐完毕",
        mMedicationLabel: "待用药项",
        classRosterTitle: "📋 探索者小班名册",
        roomLabel: "102 教室",
        thChildName: "幼儿姓名",
        thAge: "年龄",
        thMeal: "用餐",
        thNap: "午睡",
        thMedication: "用药状态",
        statusMeal100: "✔ 100% 用餐完成",
        statusMeal75: "✔ 75% 用餐完成",
        statusPending14: "等待中 (14:00)",
        statusPending16: "等待中 (16:00)",
        statusNone: "无",
        logEntryTitle: "✍️ 记录录入与家园同步",
        lblSelectChild: "选择幼儿",
        lblMealStatus: "午餐记录状态",
        optMeal100: "午餐: 100% 完成",
        optMeal75: "午餐: 75% 完成",
        optMeal50: "午餐: 50% 完成",
        btnSaveNotify: "保存并通知家长 ➜",
        schedTitle: "📅 今日班级日程",
        schedItem1: "🎨 晨间手工与美术",
        schedItem2: "🥗 营养午餐服务",
        schedItem3: "💤 午睡与休息时间",
        liveStreamTitle: "⚡ 家长实时动态流",
        mTotalResidents: "住长者总数",
        mActiveInfirmary: "医务室活跃床位",
        mVitalsChecked: "已检测体征",
        mMedAlerts: "紧急用药提醒",
        residentVitalsTitle: "👵 长者生命体征健康监测",
        thResident: "长者姓名",
        thRoom: "房间号",
        thBP: "血压",
        thPulse: "脉搏",
        thBloodSugar: "血糖",
        medFormTitle: "💊 快捷用药记录",
        lblResident: "选择长者",
        lblMedType: "药物类型",
        btnLogMed: "记录用药并通知医生 ➜",
        familyFeedTitle: "👨‍👩‍👧 米拉·伊尔马兹 家长动态",
        familyFeedDesc: "今日日程摘要与实时更新:",
        msgTeacherTitle: "📩 给教师留言 / 托药申请",
        lblMessageNote: "给教师的留言",
        btnSendTeacher: "发送留言 ➜",
        mRevenueLabel: "月度收入",
        mOccupancyLabel: "入住率",
        mActiveStaff: "在岗员工",
        mSatisfaction: "家长满意度",
        mgrReportsTitle: "📊 机构财务与运营报告",
        mgrReportsDesc: "导出月度账单、入住率报告与员工日志:",
        btnExportPdf: "导出 PDF 报告 📄",
        btnMassSms: "发送群发公告 📱",
        staffStatusTitle: "👥 员工值班状态",
        btnExitApp: "🚪 返回 Landing Page",
        btnLandingPage: "Landing Page ➜"`;

// Insert the key strings into fullDictionary
html = html.replace('cardManagerSub: "Financial Reports, Mass SMS & PDF Generation"', 'cardManagerSub: "Financial Reports, Mass SMS & PDF Generation",' + saasKeysEn);
html = html.replace('cardManagerSub: "Finansal Raporlar, Toplu SMS & PDF Oluşturucu"', 'cardManagerSub: "Finansal Raporlar, Toplu SMS & PDF Oluşturucu",' + saasKeysTr);
html = html.replace('cardManagerSub: "Informes Financieros, SMS Masivos y PDF"', 'cardManagerSub: "Informes Financieros, SMS Masivos y PDF",' + saasKeysEs);
html = html.replace('cardManagerSub: "财务报告、群发短信与 PDF 生成"', 'cardManagerSub: "财务报告、群发短信与 PDF 生成",' + saasKeysZh);

fs.writeFileSync(htmlPath, html, 'utf8');
console.log('Successfully added all SaaS keys to fullDictionary in landing-page.html!');
